%YAML:1.0
date: "Wed Dec 17 06:52:30 2014\n"
nodes:
   -
      ind: 0
      typeid: "bm::VimJay"
      name: graph
      loc: [ 40., 5.0599990844726562e+01 ]
      inputs:
         -
            type: 1
            name: enable
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: force_update
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: out
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: in
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: decor
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: mode
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: x
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: y
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: w
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: h
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: node_ind
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 5
            name: node
            src_ind: -1
            src_port: ""
         -
            type: 5
            name: graph_file
            src_ind: -1
            src_port: ""
         -
            type: 5
            name: graph_out
            src_ind: -1
            src_port: ""
   -
      ind: 1
      typeid: "bm::Output"
      name: output
      loc: [ 4.0199981689453125e+01, 2.9049987792968750e+02 ]
      inputs:
         -
            type: 1
            name: enable
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: force_update
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: out
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: in
            src_ind: 3
            src_port: out
         -
            type: 1
            name: decor
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: mode
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: x
            value: 1280.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: y
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: w
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: h
            value: 0.
            src_ind: -1
            src_port: ""
   -
      ind: 2
      typeid: "bm::Output"
      name: preview
      loc: [ 4.0199981689453125e+01, 4.8029998779296875e+02 ]
      inputs:
         -
            type: 1
            name: enable
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: force_update
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: out
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: in
            src_ind: 3
            src_port: out
         -
            type: 1
            name: decor
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: mode
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: x
            value: 1280.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: y
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: w
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: h
            value: 0.
            src_ind: -1
            src_port: ""
   -
      ind: 3
      typeid: "bm::ImageDir"
      name: image_dir
      loc: [ 220., 50. ]
      dir: /home/lucasw/catkin_ws/src/vimjay/data
      inputs:
         -
            type: 1
            name: enable
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: force_update
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: out
            src_ind: -1
            src_port: ""
         -
            type: 2
            name: in
            src_ind: -1
            src_port: ""
         -
            type: 3
            name: out
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: max_size
            value: 100.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: cur_size
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: mode
            value: 0.
            src_ind: -1
            src_port: ""
         -
            type: 1
            name: keep_aspect
            value: 1.
            src_ind: -1
            src_port: ""
         -
            type: 5
            name: dir
            src_ind: -1
            src_port: ""
         -
            type: 5
            name: name
            src_ind: -1
            src_port: ""
